import pandas as pd
import numpy as np

df = pd.read_csv("/Users/krishnamahajan/Documents/LabMentix/Flipkart Project/Customer_support_data.csv")

print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)
print(f"Shape: {df.shape[0]} rows x {df.shape[1]} columns")
print()

print("=" * 60)
print("MISSING VALUES")
print("=" * 60)
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"Missing Count": missing, "Missing %": missing_pct})
print(missing_df[missing_df["Missing Count"] > 0].to_string())
print()

print("=" * 60)
print("CSAT SCORE DISTRIBUTION")
print("=" * 60)
print(df["CSAT Score"].value_counts().sort_index().to_string())
print(f"\nMean CSAT: {df['CSAT Score'].mean():.3f}")
print(f"Median CSAT: {df['CSAT Score'].median()}")
print(f"Std CSAT: {df['CSAT Score'].std():.3f}")
print()

print("=" * 60)
print("CHANNEL NAME DISTRIBUTION")
print("=" * 60)
print(df["channel_name"].value_counts().to_string())
print()

print("=" * 60)
print("CATEGORY DISTRIBUTION")
print("=" * 60)
print(df["category"].value_counts().to_string())
print()

print("=" * 60)
print("TOP 10 SUB-CATEGORIES")
print("=" * 60)
print(df["Sub-category"].value_counts().head(10).to_string())
print()

print("=" * 60)
print("AGENT SHIFT DISTRIBUTION")
print("=" * 60)
print(df["Agent Shift"].value_counts().to_string())
print()

print("=" * 60)
print("TENURE BUCKET DISTRIBUTION")
print("=" * 60)
print(df["Tenure Bucket"].value_counts().to_string())
print()

print("=" * 60)
print("AVG CSAT BY CHANNEL")
print("=" * 60)
print(df.groupby("channel_name")["CSAT Score"].mean().round(3).to_string())
print()

print("=" * 60)
print("AVG CSAT BY CATEGORY")
print("=" * 60)
print(df.groupby("category")["CSAT Score"].mean().round(3).sort_values().to_string())
print()

print("=" * 60)
print("AVG CSAT BY AGENT SHIFT")
print("=" * 60)
print(df.groupby("Agent Shift")["CSAT Score"].mean().round(3).to_string())
print()

print("=" * 60)
print("AVG CSAT BY TENURE BUCKET")
print("=" * 60)
print(df.groupby("Tenure Bucket")["CSAT Score"].mean().round(3).sort_values().to_string())
print()

print("=" * 60)
print("CONNECTED HANDLING TIME STATS")
print("=" * 60)
cht = df["connected_handling_time"].dropna()
print(f"Count (non-null): {len(cht)}")
print(f"Mean: {cht.mean():.2f}")
print(f"Median: {cht.median():.2f}")
print(f"Min: {cht.min():.2f}")
print(f"Max: {cht.max():.2f}")
print()

print("=" * 60)
print("ITEM PRICE STATS")
print("=" * 60)
ip = df["Item_price"].dropna()
print(f"Count (non-null): {len(ip)}")
print(f"Mean: {ip.mean():.2f}")
print(f"Median: {ip.median():.2f}")
print(f"Min: {ip.min():.2f}")
print(f"Max: {ip.max():.2f}")
print()

print("=" * 60)
print("TOP 10 AGENTS BY TICKET COUNT")
print("=" * 60)
print(df["Agent_name"].value_counts().head(10).to_string())
print()

print("=" * 60)
print("TOP 10 MANAGERS BY TICKET COUNT")
print("=" * 60)
print(df["Manager"].value_counts().head(10).to_string())
print()

print("=" * 60)
print("AVG CSAT BY MANAGER (top 10 by ticket volume)")
print("=" * 60)
top_mgrs = df["Manager"].value_counts().head(10).index
print(df[df["Manager"].isin(top_mgrs)].groupby("Manager")["CSAT Score"].mean().round(3).sort_values().to_string())
print()

print("=" * 60)
print("CSAT SCORE: LOW (<=2) vs HIGH (>=4)")
print("=" * 60)
low = (df["CSAT Score"] <= 2).sum()
high = (df["CSAT Score"] >= 4).sum()
neutral = ((df["CSAT Score"] == 3)).sum()
print(f"Low (1-2): {low} ({low/len(df)*100:.1f}%)")
print(f"Neutral (3): {neutral} ({neutral/len(df)*100:.1f}%)")
print(f"High (4-5): {high} ({high/len(df)*100:.1f}%)")
print()

# Response time calculation
try:
    df["Issue_reported at"] = pd.to_datetime(df["Issue_reported at"], format="%d/%m/%Y %H:%M", errors="coerce")
    df["issue_responded"] = pd.to_datetime(df["issue_responded"], format="%d/%m/%Y %H:%M", errors="coerce")
    df["response_time_min"] = (df["issue_responded"] - df["Issue_reported at"]).dt.total_seconds() / 60
    rt = df["response_time_min"].dropna()
    print("=" * 60)
    print("RESPONSE TIME (minutes)")
    print("=" * 60)
    print(f"Count (non-null): {len(rt)}")
    print(f"Mean: {rt.mean():.2f} min")
    print(f"Median: {rt.median():.2f} min")
    print(f"Min: {rt.min():.2f} min")
    print(f"Max: {rt.max():.2f} min")
    print()

    print("=" * 60)
    print("AVG RESPONSE TIME BY CATEGORY")
    print("=" * 60)
    print(df.groupby("category")["response_time_min"].mean().round(2).sort_values(ascending=False).to_string())
    print()

    print("=" * 60)
    print("CORRELATION: RESPONSE TIME vs CSAT")
    print("=" * 60)
    corr = df[["response_time_min", "CSAT Score"]].corr()
    print(corr.to_string())
    print()
except Exception as e:
    print(f"Response time calc error: {e}")
